#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import print_function
from keyids import KEYIDS
from Components.config import config

keyBindings = {}

keyDescriptions = [{  # id=0 - dmm0 remote directory, DM8000.
	# However, the dmm0 rcpositions.xml file should define
	# an <rc id=0 /> element, but it does not, it only has
	# an <rc id=2 /> element.
	#
	# The rcpositions.xml file defines <button/> elements,
	# but they do not appear to emit codes.
	KEYIDS["BTN_0"]: ("UP", "fp"),
	KEYIDS["BTN_1"]: ("DOWN", "fp"),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_AUDIO"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_BOOKMARKS"]: ("PLUGIN",),
	KEYIDS["KEY_CHANNELDOWN"]: ("BOUQUET-",),
	KEYIDS["KEY_CHANNELUP"]: ("BOUQUET+",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_EDIT"]: ("EPGSETUP",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_FASTFORWARD"]: ("FORWARD",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_HELP"]: ("HELP",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_LAST"]: ("BACK",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_MEDIA"]: ("MEDIA",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_NEXT"]: ("ARROWRIGHT",),
	KEYIDS["KEY_NEXTSONG"]: ("NEXTSONG",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_PLAYPAUSE"]: ("PLAYPAUSE",),
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_PREVIOUS"]: ("ARROWLEFT",),
	KEYIDS["KEY_PREVIOUSSONG"]: ("PREVIOUSSONG",),
	KEYIDS["KEY_PROGRAM"]: ("TIMER",),
	KEYIDS["KEY_RADIO"]: ("RADIO",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_SCREEN"]: ("SCREEN",),
	KEYIDS["KEY_SEARCH"]: ("WWW",),
	KEYIDS["KEY_SLEEP"]: ("SLEEP",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_TV"]: ("TV",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_VIDEO"]: ("PVR",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOL-",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOL+",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",)
}, {  # id=1 - dmm0 remote directory, other than DM8000.
	# However, the dmm0 rcpositions.xml file should define
	# an <rc id=1 /> element, but it does not, it only has
	# an <rc id=2 /> element.
	#
	# The rcpositions.xml file defines <button/> elements,
	# but they do not appear to emit codes.
	KEYIDS["BTN_0"]: ("UP", "fp"),
	KEYIDS["BTN_1"]: ("DOWN", "fp"),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_AUDIO"]: ("AUDIO",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_BOOKMARKS"]: ("PLUGIN",),
	KEYIDS["KEY_CHANNELDOWN"]: ("BOUQUET-",),
	KEYIDS["KEY_CHANNELUP"]: ("BOUQUET+",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_EDIT"]: ("EPGSETUP",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_FASTFORWARD"]: ("BLUE", "SHIFT"),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_HELP"]: ("HELP",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_LAST"]: ("BACK",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_MEDIA"]: ("MEDIA",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_NEXT"]: ("ARROWRIGHT",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_PLAY"]: ("GREEN", "SHIFT"),
	KEYIDS["KEY_PAUSE"]: ("YELLOW", "SHIFT"),
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_PREVIOUS"]: ("ARROWLEFT",),
	KEYIDS["KEY_PROGRAM"]: ("TIMER",),
	KEYIDS["KEY_RADIO"]: ("RADIO",),
	KEYIDS["KEY_RECORD"]: ("RADIO", "SHIFT"),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_REWIND"]: ("RED", "SHIFT"),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_SCREEN"]: ("SCREEN",),
	KEYIDS["KEY_SEARCH"]: ("WWW",),
	KEYIDS["KEY_SLEEP"]: ("SLEEP",),
	KEYIDS["KEY_STOP"]: ("TV", "SHIFT"),
	KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_TV"]: ("TV",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_VIDEO"]: ("PVR",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOL-",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOL+",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",)
}, {  # id=2 - Everything else.
	KEYIDS["BTN_0"]: ("UP", "fp"),
	KEYIDS["BTN_1"]: ("DOWN", "fp"),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_ARCHIVE"]: ("HISTORY",),
	KEYIDS["KEY_AUDIO"]: ("AUDIO",),
	KEYIDS["KEY_AUX"]: ("WIZTV",),
	KEYIDS["KEY_BACK"]: ("RECALL",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_BOOKMARKS"]: ("PLUGIN",),
	KEYIDS["KEY_CALENDAR"]: ("AUTOTIMER",),
	KEYIDS["KEY_CHANNELDOWN"]: ("BOUQUET-",),
	KEYIDS["KEY_CHANNELUP"]: ("BOUQUET+",),
	KEYIDS["KEY_CONTEXT_MENU"]: ("CONTEXT",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_EJECTCD"]: ("EJECTCD",),
	KEYIDS["KEY_END"]: ("END",),
	KEYIDS["KEY_ENTER"]: ("ENTER", "kbd"),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_F1"]: ("F1",),
	KEYIDS["KEY_F2"]: ("F2",),
	KEYIDS["KEY_F3"]: ("F3",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_FILE"]: ("LIST",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_HELP"]: ("HELP",),
	KEYIDS["KEY_HOME"]: ("HOME",),
	KEYIDS["KEY_HOMEPAGE"]: ("HOMEPAGE",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_LAST"]: ("BACK",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_LIST"]: ("PLAYLIST",),
	KEYIDS["KEY_MEDIA"]: ("MEDIA",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_MODE"]: ("VKEY",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_NEXT"]: ("ARROWRIGHT",),
	KEYIDS["KEY_NEXTSONG"]: ("NEXTSONG",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_OPTION"]: ("OPTION",),
	KEYIDS["KEY_PAGEDOWN"]: ("PAGEDOWN",),
	KEYIDS["KEY_PAGEUP"]: ("PAGEUP",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_PC"]: ("LAN",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_PLAYPAUSE"]: ("PLAYPAUSE",),
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_PREVIOUS"]: ("ARROWLEFT",),
	KEYIDS["KEY_PREVIOUSSONG"]: ("PREVIOUSSONG",),
	KEYIDS["KEY_PROGRAM"]: ("TIMER",),
	KEYIDS["KEY_PVR"]: ("PVR",),
	KEYIDS["KEY_QUESTION"]: ("ABOUT",),
	KEYIDS["KEY_RADIO"]: ("RADIO",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_SAT"]: ("SAT",),
	KEYIDS["KEY_SCREEN"]: ("SCREEN",),
	KEYIDS["KEY_SEARCH"]: ("WWW",),
	KEYIDS["KEY_SETUP"]: ("SETUP",),
	KEYIDS["KEY_SLEEP"]: ("SLEEP",),
	KEYIDS["KEY_SLOW"]: ("SLOW",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
	KEYIDS["KEY_SWITCHVIDEOMODE"]: ("VMODE",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_TIME"]: ("TIMESHIFT",),
	KEYIDS["KEY_TV"]: ("TV",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_VIDEO"]: ("VIDEO",),
	# KEYIDS["KEY_VMODE"]: ("VMODE",),  # This value is deprecated use KEY_SWITCHVIDEOMODE instead.
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOL-",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOL+",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_ZOOM"]: ("ZOOM",),
	# Discrete power codes
	KEYIDS["KEY_POWER2"]: ("POWER2",),
	KEYIDS["KEY_SUSPEND"]: ("SUSPEND",),
	KEYIDS["KEY_WAKEUP"]: ("WAKEUP",)
}, {  # id=3 - Spark HOF-12D
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_SWITCHVIDEOMODE"]: ("V.FORMAT",),
	KEYIDS["KEY_AUX"]: ("TV/SAT",),
	KEYIDS["KEY_PROGRAM"]: ("TIME",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_TV2"]: ("TV/RADIO",),
	KEYIDS["KEY_BACK"]: ("RECALL",),
	KEYIDS["KEY_CHANNELUP"]: ("PAGE+",),
	KEYIDS["KEY_CHANNELDOWN"]: ("PAGE-",),
	KEYIDS["KEY_SUBTITLE"]: ("FIND",),
	KEYIDS["KEY_FILE"]: ("FOLDER",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOL+",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOL-",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_OK"]: ("OK", ""),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_SAT"]: ("SAT",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_PREVIOUS"]: ("PREV",),
	KEYIDS["KEY_NEXT"]: ("NEXT",),
	KEYIDS["KEY_F"]: ("FAST",),
	KEYIDS["KEY_SLOW"]: ("SLOW",),
	KEYIDS["KEY_P"]: ("PLAY_MODE",),
	KEYIDS["KEY_MEDIA"]: ("USB",),
	KEYIDS["KEY_TIME"]: ("Tms",),
	KEYIDS["KEY_F1"]: ("F1",),
	KEYIDS["KEY_F2"]: ("F2",),
	KEYIDS["KEY_F3"]: ("F3",),
	KEYIDS["KEY_OPEN"]: ("PORTAL",)
}, {  # id=4 - All Fortis
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_POWER"]: ("STANDBY",),
	KEYIDS["KEY_ZOOM"]: ("V.FORMAT",),
	KEYIDS["KEY_SWITCHVIDEOMODE"]: ("RESOLUTION",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_BACK"]: ("RECALL",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOLUMEUP",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_CHANNELUP"]: ("CHANNELUP",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOLUMEDOWN",),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_CHANNELDOWN"]: ("CHANNELDOWN",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_PAGEUP"]: ("PAGEUP",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_PAGEDOWN"]: ("PAGEDOWN",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_PREVIOUS"]: ("PREVIOUS",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_NEXT"]: ("NEXT",),
	KEYIDS["KEY_FILE"]: ("PLAYLIST",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_HELP"]: ("CHECK",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_SCREEN"]: ("PIP",),
	KEYIDS["KEY_GOTO"]: ("PIP_SWAP",),
	KEYIDS["KEY_AUX"]: ("PIP_LIST",), # PIP list
	KEYIDS["KEY_PROGRAM"]: ("SLEEP",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_TV2"]: ("TVRADIO",),
	KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
}, {  # id=5 - Topfield TF77X0HDPVR
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_SWITCHVIDEOMODE"]: ("V.FORMAT",),
	KEYIDS["KEY_ZOOM"]: ("A/R",),
	KEYIDS["KEY_AUX"]: ("AUX",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_BACK"]: ("BACK",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_AUDIO"]: ("AUDIO",),
	KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_EPG"]: ("GUIDE",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_SLOW"]: ("SLOW",),
	KEYIDS["KEY_FILE"]: ("LIST" ,),
	KEYIDS["KEY_SAT"]: ("SAT",),
	KEYIDS["KEY_PREVIOUS"]: ("STEPBACK",),
	KEYIDS["KEY_NEXT"]: ("STEPFORWARD",),
	KEYIDS["KEY_SCREEN"]: ("MARK",),
	KEYIDS["KEY_TV2"]: ("TV/RADIO",),
	KEYIDS["KEY_MEDIA"]: ("USB",),
	KEYIDS["KEY_PROGRAM"]: ("TIMER",),
}, {  # id=6 - Kathrein UFS912, UFS913
	KEYIDS["KEY_HELP"]: ("HELP",),
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOLUMEDOWN",),
	KEYIDS["KEY_CHANNELUP"]: ("CHANNELUP",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOLUMEUP",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_CHANNELDOWN"]: ("CHANNELDOWN",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_FILE"]: ("ARCHIV",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_EXIT"]: ("BACK",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_MEDIA"]: ("MEDIA",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_STOP"]: ("STOP",),
}, {  # id=7 - Cuberevo universal
	KEYIDS["KEY_F1"]: ("KEY_F1",),
	KEYIDS["KEY_F2"]: ("KEY_F2",),
	KEYIDS["KEY_F3"]: ("KEY_F3",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_RADIO"]: ("RADIO",),
	KEYIDS["KEY_PREVIOUS"]: ("PREVIOUS",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_FAVORITES"]: ("FAVORITES",),
	KEYIDS["KEY_MEDIA"]: ("MEDIA",),
	KEYIDS["KEY_POWER"]: ("STANDBY",),
	KEYIDS["KEY_F5"]: ("KEY_F5",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_ARCHIVE"]: ("ARCHIVE",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_SLOW"]: ("SLOW",),
	KEYIDS["KEY_AGAIN"]: ("AGAIN",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_F7"]: ("KEY_F7",),
	KEYIDS["KEY_BOOKMARKS"]: ("KEY_BOOMARKS",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_F8"]: ("KEY_F8",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_AUDIO"]: ("AUDIO",),
	KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_CHANNELUP"]: ("CHANNELUP",),
	KEYIDS["KEY_CHANNELDOWN"]: ("CHANNELDOWN",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOLUMEUP",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOLUMEDOWN",),
	KEYIDS["KEY_WWW"]: ("WWW",)
}, {  # id=8 - Vitamin HD5000
	KEYIDS["KEY_AUX"]: ("TV/STB",),
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
	KEYIDS["KEY_F3"]: ("SIGNAL",),
	KEYIDS["KEY_PROGRAM"]: ("CAPTURE",),
	KEYIDS["KEY_F5"]: ("BOOK/M",),
	KEYIDS["KEY_SCREEN"]: ("BOOK/J",),
	KEYIDS["KEY_PREVIOUS"]: ("PREVIOUS",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_NEXT"]: ("NEXT",),
	KEYIDS["KEY_AGAIN"]: ("REPEAT",),
	KEYIDS["KEY_PLAY"]: ("PLAY/PAUSE",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_EXIT"]: ("EXIT",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_CHANNELUP"]: ("CHUP",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOLUP",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_CHANNELDOWN"]: ("CHDOWN",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOLDOWN",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_BACK"]: ("RECALL",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_SAT"]: ("SAT",),
	KEYIDS["KEY_WWW"]: ("MOSAIC",),
	KEYIDS["KEY_F11"]: ("FEED",),
	KEYIDS["KEY_TV2"]: ("TV/RADIO",),
	KEYIDS["KEY_FILE"]: ("PLAYLIST",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_F1"]: ("F1",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_F2"]: ("F2",)
}, {  # id=9 - ADB XMP
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_MEDIA"]: ("VOD",),
	KEYIDS["KEY_BACK"]: ("RECALL",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_HOME"]: ("HOME",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_TIME"]: ("APP",),
	KEYIDS["KEY_SUBTITLE"]: ("OPT",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOLUMEUP",),
	KEYIDS["KEY_CHANNELUP"]: ("CHUP",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOLUMEDOWN",),
	KEYIDS["KEY_CHANNELDOWN"]: ("CHDOWN",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_EXIT"]: ("BACK",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_TV2"]: ("ATSIGN",),
	KEYIDS["KEY_TEXT"]: ("TEXT",),
	KEYIDS["KEY_FILE"]: ("LIST",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_MENU"]: ("SETUP",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_HELP"]: ("STAR",)
}, {  # id=10 - Pace HDS7241
}, {  # id=11 - VIP2_1
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_SWITCHVIDEOMODE"]: ("V.FORMAT",),
	KEYIDS["KEY_PROGRAM"]: ("TIME",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_TIME"]: ("Tms",),
	KEYIDS["KEY_SCREEN"]: ("PIP",),
	KEYIDS["KEY_F1"]: ("F1",),
	KEYIDS["KEY_AUX"]: ("TV/SAT",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_TV2"]: ("TV/RADIO",),
	KEYIDS["KEY_BACK"]: ("RECALL",),
	KEYIDS["KEY_SUBTITLE"]: ("FIND",),
	KEYIDS["KEY_VOLUMEDOWN"]: ("VOL-",),
	KEYIDS["KEY_CHANNELDOWN"]: ("PAGEDOWN",),
	KEYIDS["KEY_SAT"]: ("SAT",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_VOLUMEUP"]: ("VOL+",),
	KEYIDS["KEY_CHANNELUP"]: ("PAGEUP",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_UP"]: ("UP",),
	KEYIDS["KEY_DOWN"]: ("DOWN",),
	KEYIDS["KEY_LEFT"]: ("LEFT",),
	KEYIDS["KEY_OK"]: ("OK",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT",),
	KEYIDS["KEY_HOME"]: ("EXIT",),
	KEYIDS["KEY_EPG"]: ("EDIVISION",),
	KEYIDS["KEY_FILE"]: ("FOLDER",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_PREVIOUS"]: ("PREVIOUS",),
	KEYIDS["KEY_NEXT"]: ("NEXT",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_SLOW"]: ("STEP_BACK",),
	KEYIDS["KEY_F"]: ("STEP_FWD",),
	KEYIDS["KEY_W"]: ("PLAYMODE",),
	KEYIDS["KEY_MEDIA"]: ("USB",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",)
}, {  # id=12 - HL101
	KEYIDS["KEY_POWER"]: ("POWER",),
	KEYIDS["KEY_TIME"]: ("PROGRAM",),
	KEYIDS["KEY_U"]: ("U",),
	KEYIDS["KEY_ZOOM"]: ("V.FORMAT",),
	KEYIDS["KEY_MUTE"]: ("MUTE",),
	KEYIDS["KEY_AUX"]: ("TV/SAT",),
	KEYIDS["KEY_TV2"]: ("TV/RADIO",),
	KEYIDS["KEY_FIND"]: ("FIND",),
	KEYIDS["KEY_FAVORITES"]: ("FAV",),
	KEYIDS["KEY_1"]: ("1",),
	KEYIDS["KEY_2"]: ("2",),
	KEYIDS["KEY_3"]: ("3",),
	KEYIDS["KEY_4"]: ("4",),
	KEYIDS["KEY_5"]: ("5",),
	KEYIDS["KEY_6"]: ("6",),
	KEYIDS["KEY_7"]: ("7",),
	KEYIDS["KEY_8"]: ("8",),
	KEYIDS["KEY_9"]: ("9",),
	KEYIDS["KEY_MENU"]: ("MENU",),
	KEYIDS["KEY_0"]: ("0",),
	KEYIDS["KEY_INFO"]: ("INFO",),
	KEYIDS["KEY_EPG"]: ("EPG",),
	KEYIDS["KEY_HOME"]: ("EXIT",),
	KEYIDS["KEY_UP"]: ("UP/P+",),
	KEYIDS["KEY_LEFT"]: ("LEFT/V-",),
	KEYIDS["KEY_OK"]: ("OK/LIST",),
	KEYIDS["KEY_RIGHT"]: ("RIGHT/V+",),
	KEYIDS["KEY_DOWN"]: ("DOWN/P-",),
	KEYIDS["KEY_BACK"]: ("RECALL",),
	KEYIDS["KEY_RECORD"]: ("RECORD",),
	KEYIDS["KEY_PLAY"]: ("PLAY",),
	KEYIDS["KEY_REWIND"]: ("REWIND",),
	KEYIDS["KEY_PAUSE"]: ("PAUSE",),
	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
	KEYIDS["KEY_STOP"]: ("STOP",),
	KEYIDS["KEY_SLOW"]: ("SLOW",),
	KEYIDS["KEY_PREVIOUS"]: ("PREVIOUS",),
	KEYIDS["KEY_NEXT"]: ("NEXT",),
	KEYIDS["KEY_FILE"]: ("ARCHIVE",),
	KEYIDS["KEY_OPTION"]: ("PIPSWAP",),
	KEYIDS["KEY_W"]: ("PLAYMODE",),
	KEYIDS["KEY_MEDIA"]: ("USB",),
	KEYIDS["KEY_AUDIO"]: ("AUDIO",),
	KEYIDS["KEY_SAT"]: ("SAT",),
	KEYIDS["KEY_F1"]: ("F1",),
	KEYIDS["KEY_F2"]: ("F2",),
	KEYIDS["KEY_RED"]: ("RED",),
	KEYIDS["KEY_GREEN"]: ("GREEN",),
	KEYIDS["KEY_YELLOW"]: ("YELLOW",),
	KEYIDS["KEY_BLUE"]: ("BLUE",)
}]

def addKeyBinding(domain, key, context, action, flags):
	keyBindings.setdefault((context, action), []).append((key, domain, flags))

def removeKeyBinding(key, context, action, wild=True):
	if wild and action == "*":
		for ctx, action in keyBindings.keys():
			if ctx == context:
				removeKeyBinding(key, context, action, False)
		return
	contextAction = (context, action)
	if contextAction in keyBindings:
		bind = [x for x in keyBindings[contextAction] if x[0] != key]
		if bind:
			keyBindings[contextAction] = bind
		else:
			del keyBindings[contextAction]

# Returns a list of (key, flags) for a specified action.
#
def queryKeyBinding(context, action):
	if (context, action) in keyBindings:
		return [(x[0], x[2]) for x in keyBindings[(context, action)]]
	else:
		return []

def getKeyDescription(key):
	rcType = config.plugins.remotecontroltype.rctype.value
	print("[KeyBindings] RC type is:", rcType)
	if rcType == 10:	# Spark
		idx = 3
	elif rcType == 7:	# Fortis FS9000/FS9200/HS8200
		idx = 4
	elif rcType == 8:	# Fortis HS9510/HS7420/HS7429/HS7810A/HS7819
		idx = 4
	elif rcType == 9:	# Fortis HS7110/HS7119
		idx = 4
	elif rcType == 11:	# Topfield TF77X0HDPVR
		idx = 5
	elif rcType == 12:	# Kathrein UFS912, UFS913
		idx = 6
	elif rcType == 13:	# CubeRevo Universal
		idx = 7
	elif rcType == 14:	# Vitamin HD5000
		idx = 8
	elif rcType == 15:	# ADB XMP
		idx = 9
	elif rcType == 16:	# Pace 7241
		idx = 10
	elif rcType == 17:	# Edision argus
		idx = 11
	elif rcType == 18:	# HL101
		idx = 12
	elif rcType == 19:	# Forever
		idx = 13
	else:
		idx = 2
	return keyDescriptions[idx].get(key)

def getKeyBindingKeys(filterfn=lambda key: True):
	return filter(filterfn, keyBindings)

# Remove all entries of domain "domain".
#
def removeKeyBindings(domain):
	for x in keyBindings:
		keyBindings[x] = filter(lambda e: e[1] != domain, keyBindings[x])
